name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no ec2-user@16.170.246.200 << 'EOF'
          cd /home/ec2-user/node-hello-world
          git pull origin main
          docker build -t node-hello-world .
          docker stop node-app || true
          docker rm node-app || true
          docker run -d --name node-app -p 3000:3000 node-hello-world
          EOF

